const { equal } = require('assert')
const { compile } = require('../..')

console.time('modifiers')

equal(compile('{"Hello World" | uppercase}')({}, html => html), 'HELLO WORLD')
equal(compile('{foo | uppercase}')({ foo: 'bar' }, html => html), 'BAR')
equal(compile('<div html="{foo | uppercase}"></div>')({ foo: 'bar' }), '<div>BAR</div>')
equal(compile('<div text="{foo | uppercase}"></div>')({ foo: 'bar' }, html => html), '<div>BAR</div>')
equal(compile('<div class="{foo | uppercase}"></div>')({ foo: 'bar' }, html => html), '<div class="BAR"></div>')
equal(compile('<input checked="{query | trim}">')({ query: '' }, html => html), '<input>')
equal(compile('<input checked="{query | trim}">')({ query: '   ' }, html => html), '<input>')
equal(compile('<input checked="{query | trim}">')({ query: 'bar' }, html => html), '<input checked>')
equal(compile('{foo | whitespacestrip}')({ foo: 'b  ar' }, html => html), 'bar')
equal(compile('{foo | uppercase}')({ foo: 'bar' }, html => html), 'BAR')
equal(compile('{foo | upcase}')({ foo: 'bar' }, html => html), 'BAR')
equal(compile('{foo | lowercase}')({ foo: 'BAR' }, html => html), 'bar')
equal(compile('{foo | downcase}')({ foo: 'BAR' }, html => html), 'bar')
equal(compile('{foo | dasherize}')({ foo: 'foo_bar' }, html => html), 'foo-bar')
equal(compile('{foo | constantize}')({ foo: 'bar' }, html => html), 'BAR')
equal(compile('{foo | underscore}')({ foo: 'foo-bar' }, html => html), 'foo_bar')
equal(compile('{foo | capitalize}')({ foo: 'bar' }, html => html), 'Bar')
equal(compile('{foo | unescape}')({ foo: '&amp;' }, html => html), '&')
equal(compile('{foo | lowerfirst}')({ foo: 'FOO' }, html => html), 'fOO')
equal(compile('{foo | uncapitalize}')({ foo: 'FOO' }, html => html), 'fOO')
equal(compile('{foo | humanize}')({ foo: 'foo_bar' }, html => html), 'Foo bar')
equal(compile('{foo | titleize}')({ foo: 'foo bar' }, html => html), 'Foo Bar')
equal(compile('{foo | titlecase}')({ foo: 'foo bar' }, html => html), 'Foo Bar')
equal(compile('{foo | classify}')({ foo: 'foobar' }, html => html), 'Foobar')
equal(compile('{foo | pluralize}')({ foo: 'word' }, html => html), 'words')
equal(compile('{foo | singularize}')({ foo: 'words' }, html => html), 'word')
equal(compile('{foo | swapcase}')({ foo: 'BaR' }, html => html), 'bAr')
equal(compile('{foo | camelize}')({ foo: 'bar_baz' }, html => html), 'barBaz')
equal(compile('{foo | singlespace}')({ foo: 'bar   baz' }, html => html), 'bar baz')
equal(compile('{foo | repeat(2)}')({ foo: 'fooBar' }, html => html), 'fooBarfooBar')
equal(compile('{foo | summarize(3)}')({ foo: 'foo bar' }, html => html), 'foo bar...')
equal(compile(`{foo | wrap('"')}`)({ foo: 'foo bar' }, html => html), '"foo bar"')
equal(compile(`{foo | wrap('„', '”')}`)({ foo: 'foo bar' }, html => html), '„foo bar”')
equal(compile(`{foo | unwrap('"')}`)({ foo: '"foo bar"' }, html => html), 'foo bar')
equal(compile(`{foo | unwrap('„', '”')}`)({ foo: '„foo bar”' }, html => html), 'foo bar')
equal(compile(`{foo | quote}`)({ foo: 'foo bar' }, html => html), '"foo bar"')
equal(compile(`{foo | quote('pl')}`)({ foo: 'foo bar' }, html => html), '„foo bar”')
equal(compile(`{foo | unquote}`)({ foo: '„foo bar”' }, html => html), 'foo bar')
equal(compile(`{foo | unquote}`)({ foo: '"foo bar"' }, html => html), 'foo bar')
equal(compile(`{foo | replace('bar', 'baz')}`)({ foo: 'foo baz' }, html => html), 'foo baz')
equal(compile(`{foo | replace(${/\s/g},'')}`)({ foo: 'foo baz' }, html => html), 'foobaz')
equal(compile(`{foo | strip}`)({ foo: ' foo baz ' }, html => html), 'foo baz')
equal(compile(`{foo | strip('baz')}`)({ foo: 'foo baz' }, html => html), 'foo')
equal(compile(`{foo | strip('o')}`)({ foo: 'foo' }, html => html), 'f')
equal(compile(`{foo | strip(['o', 'a'])}`)({ foo: 'foo bar' }, html => html), 'f br')
equal(compile(`{foo | squeeze}`)({ foo: 'yellow moon' }, html => html), 'yelow mon')
equal(compile(`{foo | squeeze('a-o')}`)({ foo: 'foo baar baazz  ban' }, html => html), 'fo bar bazz ban')
equal(compile(`{foo | index('ello')}`)({ foo: 'hello world' }, html => html), '1')
equal(compile(`{foo | chop}`)({ foo: 'foo barz' }, html => html), 'foo bar')
equal(compile(`{foo | chomp('barz') | trim}`)({ foo: 'foo barz' }, html => html), 'foo')
equal(compile(`{foo | dot}`)({ foo: 'foo bar ban' }, html => html), 'foo bar ban.')
equal(compile(`{foo | crop(10)}`)({ foo: 'foo bar ban baz' }, html => html), 'foo bar...')
equal(compile(`{foo | slugify('_')}`)({ foo: 'loremIpsum dolor $pec!al chars' }, html => html), 'loremipsum_dolor_pecal_chars')
equal(compile(`{foo | hyphenate}`)({ foo: '%# lorem ipsum  ? $  dolor' }, html => html), 'lorem-ipsum-dolor')
equal(compile(`{foo | initials}`)({ foo: 'Foo Bar' }, html => html), 'FB')
equal(compile(`{foo | initials(".")}`)({ foo: 'Foo Bar' }, html => html), 'F.B')
equal(compile(`{foo | tail}`)({ foo: 'Lorem ipsum dolor sit amet, consectetur' }, html => html), '...dolor sit amet, consectetur')
equal(compile(`{foo | htmlstrip}`)({ foo: 'Hello <b><i>world!</i></b>'}, html => html), 'Hello world!')
equal(compile('{foo | abs}')({ foo: -1 }, html => html), '1')
equal(compile('{foo | ceil}')({ foo: 1.6 }, html => html), '2')
equal(compile('{foo | floor}')({ foo: 1.6 }, html => html), '1')
equal(compile('{foo | round}')({ foo: 1.4 }, html => html), '1')
equal(compile('{foo | round}')({ foo: 1.6 }, html => html), '2')
equal(compile('{foo | factorial}')({ foo: 3 }, html => html), '6')
equal(compile('{foo | square}')({ foo: 4 }, html => html), '16')
equal(compile('{foo | trunc}')({ foo: 13.33 }, html => html), '13')
equal(compile('{foo | pow(3)}')({ foo: 2 }, html => html), '8')
equal(compile('{foo | truncate(6)}')({ foo: 'foobarbaz' }, html => html), 'foo...')
equal(compile('{foo | abbreviate(6)}')({ foo: 'foobarbaz' }, html => html), 'foo...')
equal(compile('{foo | pad("0")}')({ foo: 'foo\nbar' }, html => html), '0foo\n0bar')
equal(compile('{foo | max}')({ foo: [1, 2, 3] }, html => html), '3')
equal(compile('{foo | min}')({ foo: [1, 2, 3] }, html => html), '1')
equal(compile('{foo | sqrt}')({ foo: 4 }, html => html), '2')
equal(compile('{foo | add(10)}')({ foo: 5 }, html => html), 15)
equal(compile('{foo | plus(10)}')({ foo: 5 }, html => html), 15)
equal(compile('{foo | subtract(10)}')({ foo: 5 }, html => html), -5)
equal(compile('{foo | minus(10)}')({ foo: 5 }, html => html), -5)
equal(compile('{foo | multiply(10)}')({ foo: 5 }, html => html), 50)
equal(compile('{foo | divide(10)}')({ foo: 5 }, html => html), 1 / 2)
equal(compile('{foo | modulo(10)}')({ foo: 5 }, html => html), 5)
equal(compile('{foo | increment}')({ foo: 5 }, html => html), 6)
equal(compile('{foo | decrement}')({ foo: 5 }, html => html), 4)
equal(compile('{foo | clamp(2, 8)}')({ foo: 10 }, html => html), 8)
equal(compile('{foo | clamp(2, 8)}')({ foo: 6 }, html => html), 6)
equal(compile('{foo | int}')({ foo: 10 }, html => html), 10)
equal(compile('{foo | float}')({ foo: 10.25 }, html => html), 10.25)
equal(compile('{foo | percentage}')({ foo: 0.25 }, html => html), '25%')
equal(compile('{foo | fixed}')({ foo: 10.5 }, html => html), '11')
equal(compile('{foo | fixed(2)}')({ foo: 100.521 }, html => html), '100.52')
equal(compile('{foo | monetize}')({ foo: 25 }, html => html), '25,00 zł')
equal(compile('{foo | reverse}')({ foo: 'bar' }, html => html), 'rab')
equal(compile('{foo | rotate}')({ foo: 'bar' }, html => html), 'bar')
equal(compile('{foo | rotate(1)}')({ foo: [1, 2, 3] }, html => html), [2, 3, 1])
equal(compile('{foo | reverse}')({ foo: [1, 2, 3, 4] }, html => html), [4, 3, 2, 1])
equal(compile('{foo | size}')({ foo: 'bar' }, html => html), '3')
equal(compile('{foo | size}')({ foo: [1, 2] }, html => html), '2')
equal(compile('{foo | size}')({ foo: new Set([1, 2, 3]) }, html => html), '3')
equal(compile('{foo | count}')({ foo: 'bar' }, html => html), '3')
equal(compile('{foo | count}')({ foo: [1, 2] }, html => html), '2')
equal(compile('{foo | count}')({ foo: new Set([1, 2, 3]) }, html => html), '3')
equal(compile('{foo | length}')({ foo: 'bar' }, html => html), '3')
equal(compile('{foo | length}')({ foo: [1, 2] }, html => html), '2')
equal(compile('{foo | length}')({ foo: new Set([1, 2, 3]) }, html => html), '3')
equal(compile('{foo | drop(2)}')({ foo: [1, 2, 3 ,4] }, html => html), [3, 4])
equal(compile('{foo | take(2)}')({ foo: [1, 2, 3 ,4] }, html => html), [1, 2])
equal(compile('{foo | slice(2,4)}')({ foo: [1, 2, 3 ,4] }, html => html), [3, 4])
equal(compile('{foo | json}')({ foo: { bar: 'baz' } }, html => html), '{\n  "bar": "baz"\n}')
equal(compile('{foo | json(4)}')({ foo: { bar: 'baz' } }, html => html), '{\n    "bar": "baz"\n}')
equal(compile('{foo | inspect}')({ foo: { bar: 'baz' } }, html => html), '{\n  "bar": "baz"\n}')
equal(compile('{foo | inspect(4)}')({ foo: { bar: 'baz' } }, html => html), '{\n    "bar": "baz"\n}')
equal(compile('{foo | prettify}')({ foo: { bar: 'baz' } }, html => html), '{\n  "bar": "baz"\n}')
equal(compile('{foo | prettify(4)}')({ foo: { bar: 'baz' } }, html => html), '{\n    "bar": "baz"\n}')
equal(compile('{foo | prettify}')({ foo: '{"bar": "baz"}' }, html => html), '{\n  "bar": "baz"\n}')
equal(compile('{foo | prettify(4)}')({ foo: '{"bar": "baz"}' }, html => html), '{\n    "bar": "baz"\n}')
equal(compile('{foo | first}')({ foo: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] }, html => html), '1')
equal(compile('{foo | second}')({ foo: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] }, html => html), '2')
equal(compile('{foo | third}')({ foo: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] }, html => html), '3')
equal(compile('{foo | fourth}')({ foo: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] }, html => html), '4')
equal(compile('{foo | fifth}')({ foo: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] }, html => html), '5')
equal(compile('{foo | sixth}')({ foo: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] }, html => html), '6')
equal(compile('{foo | seventh}')({ foo: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] }, html => html), '7')
equal(compile('{foo | eigth}')({ foo: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] }, html => html), '8')
equal(compile('{foo | ninth}')({ foo: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] }, html => html), '9')
equal(compile('{foo | tenth}')({ foo: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] }, html => html), '10')
equal(compile('{foo | last}')({ foo: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] }, html => html), '10')
equal(compile('{foo | sum}')({ foo: [1, 5, 18] }, html => html), '24')
equal(compile('{foo | average}')({ foo: [1, 5, 18] }, html => html), '8')
equal(compile('{foo | mean}')({ foo: [1, 5, 18] }, html => html), '8')
equal(compile('{foo | median}')({ foo: [18, 5, 1] }, html => html), '5')
equal(compile('{foo | sample}')({ foo: [1] }, html => html), '1')
equal(compile('{foo | nth(-5)}')({ foo: [1, 2, 3, 4, 5] }, html => html), '1')
equal(compile('{foo | nth(3)}')({ foo: [1, 2, 3, 4, 5] }, html => html), '3')
equal(compile('{foo | unique}')({ foo: [1, 1, 2, 10, 2, 33] }, html => html), [1, 2, 10, 33])
equal(compile('{foo | compact}')({ foo: [0, 1, false, 2, '', 3] }, html => html), [1, 2, 3])
equal(compile('{foo | split(",")}')({ foo: 'foo,bar' }, html => html), ['foo', 'bar'])
equal(compile('{foo | split(",") | first}')({ foo: 'foo,bar' }, html => html), 'foo')
equal(compile('{foo | split(",") | second}')({ foo: 'foo,bar' }, html => html), 'bar')
equal(compile('{foo | dig("bar.baz")}')({ foo: { bar: {} } }, html => html), 'null')
equal(compile('{foo | dig("bar.baz")}')({ foo: { bar: { baz: 'qux' } } }, html => html), 'qux')
equal(compile('{foo | format}')({ foo: new Date('2018/05/25') }, html => html), '25-05-2018')
equal(compile('{foo | format("DD.MM.YYYY")}')({ foo: new Date('2018-05-25') }, html => html), '25.05.2018')
equal(compile('{foo | format("MM.YYYY")}')({ foo: '2018/05/25' }, html => html), '05.2018')
equal(compile('{foo | day}')({ foo: new Date('2018/05/29') }, html => html), 29)
equal(compile('{foo | weekday}')({ foo: new Date('2018-05-29') }, html => html), 2)
equal(compile('{foo | month}')({ foo: '2018/05/29' }, html => html), 4)
equal(compile('{foo | year}')({ foo: '2018/05/29' }, html => html), 2018)
equal(compile('{foo | prettydate}')({ foo: new Date(2018, 5, 29) }, html => html), 'Friday, 29th of June 2018')
equal(compile('{foo | prettydate}')({ foo: new Date(2018, 5, 29) }, html => html), 'Friday, 29th of June 2018')
equal(compile('{foo | prettydate}')({ foo: new Date(2018, 5, 29) }, html => html), 'Friday, 29th of June 2018')
equal(compile('{foo | timestamp}')({ foo: new Date(2018, 5, 29) }, html => html), '2018-06-29')
equal(compile('{foo | timestamp("YYYY/MM/DD")}')({ foo: new Date(2018, 5, 29) }, html => html), '2018/06/29')
equal(compile('{foo | celsius}')({ foo: '70°F' }, html => html), '21°C')
equal(compile('{foo | fahrenheit}')({ foo: '21°C' }, html => html), '70°F')
equal(compile('{foo | kelvin}')({ foo: '70°F' }, html => html), '294K')
equal(compile('{new Date(2018, 5, 29) | prettydate}')({}, html => html), 'Friday, 29th of June 2018')
equal(compile('{new Date(foo, bar, baz) | prettydate}')({ foo: 2018, bar: 5, baz: 29 }, html => html), 'Friday, 29th of June 2018')
equal(compile('{photos | first | dig("src")}')({
  photos: [ { size: '100', src: 'baz' }, { size: '200', src: 'qux' } ]
}, html => html), 'baz')
equal(compile('{foo | first | dig("foo.bar.baz")}')({
  foo: [ { foo: { bar: { baz: 'qux' } } }, { foo: { bar: { baz: 'quux' } } } ]
}, html => html), 'qux')
equal(compile('{foo | values }')({
  foo: { bar: 1, baz: 2, ban: 'qux' }
}, html => html), [1, 2, 'qux'])
equal(compile('{foo | values | first}')({
  foo: { bar: 1, baz: 2, ban: 'qux' }
}, html => html), '1')
equal(compile('{foo | keys }')({
  foo: { bar: 1, baz: 2, ban: 'qux' }
}, html => html), ['bar', 'baz', 'ban'])
equal(compile('{foo | keys | last}')({
  foo: { bar: 1, baz: 2, ban: 'qux' }
}, html => html), 'ban')
equal(compile('{foo | monetize({ symbol: "$", ending: false, space: false , separator: "."})}')({foo: 100}, html => html), '$100.00')

console.timeEnd('modifiers')
