const assert = require('assert')
const { extract } = require('./string')

assert.deepEqual(extract('foo'), [{ value: 'foo' }])
assert.deepEqual(extract('bar'), [{ value: 'bar' }])
assert.deepEqual(extract('{foo}'), [{ value: '{foo}' }])
assert.deepEqual(extract('{bar}'), [{ value: '{bar}' }])
assert.deepEqual(extract('foo bar'), [{ value: 'foo bar' }])
assert.deepEqual(extract('foo {bar}'), [{ value: 'foo '}, { value: '{bar}' }])
assert.deepEqual(extract('{foo} bar'), [{ value: '{foo}'}, { value: ' bar' }])
assert.deepEqual(extract('{foo} {bar}'), [{ value: '{foo}' }, { value: ' ' }, { value: '{bar}' }])
assert.deepEqual(extract('foo bar {baz}'), [{ value: 'foo bar ' }, { value: '{baz}' }])
assert.deepEqual(extract('foo {bar} baz'), [{ value: 'foo ' }, { value: '{bar}' }, { value: ' baz' }])
assert.deepEqual(extract('foo     bar'), [{ value: 'foo bar' }])
assert.deepEqual(extract('   foo     bar    '), [{ value: 'foo bar' }])
assert.deepEqual(extract('foo-{bar}'), [{ value: 'foo-'}, { value: '{bar}' }])
assert.deepEqual(extract('{foo}-{bar}'), [{ value: '{foo}' }, { value: '-' }, { value: '{bar}' }])
