name: build

on: [push, pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [24.1.0]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - name: npm install, build, and test
        run: |
          npm ci
          npm run test:debug
        env:
          CI: true
